name: Challenge2

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: artifact
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create file
        run: echo "hello world" > test.txt

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: test.txt
